distro/depends/xfstests-dev: fix xfstests pack failed
fix the following issue
------
liuyd@inn:/result/pack/xfstests-ucode=0x42d/ivb44/debian-x86_64-2018-04-03.cgz/x86_64-rhel-7.6/gcc-7/1c163f4c7b3f621efff9b28a47abb36f7378d783/0$ cat stderr
---snip---
phase5.c: In function ‘xfs_scrub_fs_label’:
phase5.c:304:11: warning: implicit declaration of function ‘unicrash_fs_label_init’ [-Wimplicit-function-declaration]
  moveon = unicrash_fs_label_init(&uc, ctx);
           ^~~~~~~~~~~~~~~~~~~~~~
phase5.o: In function `xfs_scrub_fs_label':
/tmp/build-xfstests/xfsprogs-dev/scrub/phase5.c:304: undefined reference to `unicrash_fs_label_init'
collect2: error: ld returned 1 exit status
------

the root cause is unicrash make failed,
unicrash.h has defined unicrash_fs_label_init, and phase5.c has included unicrash.h,
but when unicrash.o make failed, it will trigger undefined error
------
root@lkp-opteron1 /tmp/build-xfstests/xfsprogs-dev/scrub# gcc unicrash.c -I /tmp/build-xfstests/xfsprogs-dev/include/ -I /usr/include
unicrash.c:13:29: fatal error: unicode/ustring.h: No such file or directory
 #include <unicode/ustring.h>
                             ^
compilation terminated.
------

install libicu-dev, pack passed.
------
liuyd@inn:/result/pack/xfstests/lkp-opteron1/debian-x86_64-2018-04-03.cgz/x86_64-rhel-7.6/gcc-7/v5.0/2$ cat pack.json
{
  "pack.pass": [
    1
  ]
}
------

Signed-off-by: Liu Yiding <yidingx.liu@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>