distro/depends/tbench-dev: add necessary package to build tbench
Lack of these two packages causes config error and then causes
build error:
-----
Extracting templates from packages: 100%
In file included from dbench.c:25:0:
dbench.h:20:20: fatal error: config.h: No such file or directory
 #include "config.h"
                    ^
compilation terminated.
make: *** [dbench] Error 1
-----

So add them.

Signed-off-by: Chao Fan <fanx.chao@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>