tests/autotest: specify python2.7 to perform the test
In some cases the default version of python is 3.*, which will cause the following problems:
```
root@clear-lkp-30040~/lkp-tests # lkp run ./autotest-part2-monotonic_time.yaml     [0/1958]
2019-06-25 06:33:54 client/autotest-local run monotonic_time
Traceback (most recent call last):
  File "client/autotest-local", line 6, in <module>
    import autotest.common as common  # pylint: disable=W0611
ModuleNotFoundError: No module named 'autotest'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/lkpaddon/lkp/benchmarks/autotest/client/common.py", line 4, in <module>
    import autotest.client.setup_modules as setup_modules
ModuleNotFoundError: No module named 'autotest'
```

Signed-off-by: Zhou Hao <haox.a.zhou@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>