stats/stderr: fix stderr nil issues
In bin/post-run, stderr log size is limited to 10M

"truncate --no-create --size='<10M' $TMP/output $TMP/stdout $TMP/stderr $TMP/umesg 2>/dev/null"

When do some long time test, for example, test "memtier" for more than 2 hours, the stderr log
size is about 30M, but in post-run it will be cut to only 10M, the last line maybe just half
of logs, this will cause the following "nil" issues.

"in `should_ignore_stderr': undefined method `valid_encoding?' for nil:NilClass (NoMethodError)"

Signed-off-by: Zhengjun Xing <zhengjun.xing@linux.intel.com>
Reviewed-by: "Huang, Ying" <ying.huang@intel.com>
Signed-off-by: Philip Li <philip.li@intel.com>